os: linux

language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  - docker pull php:7.3
  - docker pull crossbario/autobahn-testsuite
  - phpenv config-rm xdebug.ini || echo "No xdebug config.";

install:
  - travis_retry composer update -n --prefer-dist

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix
  - vendor/bin/psalm
  - docker run -d --rm -v ${PWD}:/app --net="host" --name amp-websocket php:7.3 php /app/test-autobahn/server.php
  - docker run -ti --rm -v ${PWD}/test-autobahn/config:/config -v ${PWD}/test-autobahn/reports:/reports --net="host" --name fuzzingclient crossbario/autobahn-testsuite wstest -m fuzzingclient -s config/fuzzingclient.json
  - php test-autobahn/report.php

  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - travis_retry ./php-coveralls.phar -v

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
